version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_MASTER_HOST=0.0.0.0

  spark-worker-1:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-1
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_PORT=8091
      - SPARK_WORKER_WEBUI_PORT=8081

  spark-worker-2:
    image: bitnami/spark:3.5.1
    container_name: spark-worker-2
    ports:
      - "8082:8082"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_PORT=8092
      - SPARK_WORKER_WEBUI_PORT=8082

  spark-test-node:
    image: bitnami/spark:3.5.1
    container_name: spark-test-node
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077

  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-notebook
    ports:
      - "4040:4040"
      - "4041:4041"
    depends_on:
      - spark-master
    environment:
      - NOTEBOOK_PORT=4041
      - SPARK_MASTER_URL=spark://spark-master:7077