#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $READONLY_USER WITH PASSWORD '$READONLY_PASSWORD';
  GRANT CONNECT ON DATABASE $POSTGRES_DB TO $READONLY_USER;
  GRANT USAGE ON SCHEMA public TO $READONLY_USER;
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO $READONLY_USER;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $READONLY_USER;
EOSQL